FROM ubuntu:14.04
MAINTAINER Sergei Vizel <http://github.com/cravler>

# Common environment variables
ENV DEBIAN_FRONTEND noninteractive

RUN \\

# Install dependencies
    apt-get update && apt-get install -y --no-install-recommends \\
        openjdk-7-jre \\
        unzip \\
        wget \\
        ruby && \\

# Remove cache
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH \${PATH}:/opt/Sencha/Cmd/${SENCHA_CMD_VERSION}

RUN \\

# Install Sencha-CMD
    wget -O sencha-cmd.zip ${SENCHA_CMD_PACKAGE} && \\
    unzip sencha-cmd.zip && rm sencha-cmd.zip && chmod +x ${SENCHA_CMD_INSTALLER} && \\
    mkdir -p /opt/Sencha/Cmd && mv ${SENCHA_CMD_INSTALLER} /opt/Sencha/Cmd && \\
    /opt/Sencha/Cmd/${SENCHA_CMD_INSTALLER} ${SENCHA_CMD_INSTALLER_OPTIONS} ${SENCHA_CMD_COMPASS_FIX} && \\
    rm /opt/Sencha/Cmd/${SENCHA_CMD_INSTALLER}

VOLUME ["/var/www"]
WORKDIR /var/www

CMD ["bash"]
