FROM cravler/faye-app:latest

LABEL maintainer "Sergei Vizel <http://github.com/cravler>"

RUN \
\
# Install dependencies
    apk add --update \
        git \
        make \
        rsync \
    && \
    rm -rf /var/cache/apk/* && \
\
# Build Faye
    git clone https://github.com/faye/faye /faye && \
    cd /faye && \
    git checkout master && \
    npm i --save-dev webpack@^4 webpack-cli@^4 && \
    NODE_OPTIONS=--openssl-legacy-provider make && \
\
# Install
    npm install -g https://github.com/cravler/faye-app && \
    cd /usr/local/lib/node_modules/faye-app && \
    rm -rf node_modules && \
    npm i -S /faye/build && \
    npm i && \
    sed -i 's/"version": ".*"/"version": "dev"/g' package.json
